### ISSUE TITLE
[question] image licences

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [xsalazar/emoji-kitchen#190]
so im just asking, what is licence of output emojis? is it propertiary like gboard, no licence or mit same as your project?

**Comment by xsalazar** [comment]
I have no idea, I don't think Google has any official documentation around that.

Just to be clear, this repository doesn't host any images, but only has the smarts to build the public URLs where the images live, e.g. https://www.gstatic.com/android/keyboard/emojikitchen/20201001/u1f600/u1f600_u1f600.png. 

These are the same URLs that are sent to your device when typing in any input field that support stickers. See [this documentation](https://developer.android.com/guide/topics/text/image-keyboard) and the screenshot here 
![image](https://user-images.githubusercontent.com/14851080/185660981-7c5126a3-c43a-4c9b-8e37-297dce9390f3.png)

Given this, and the fact that once Gboard users have an image, they're free to post on Twitter, upload, share, etc. -- I would say exercise reasonable judgement here. It's not likely you're allowed to profit or redistribute under another name or privatize them in any way.

**Comment by hacknorris-aka-penguin** [comment]
not this. i just find these pics cool and thought about building a game about it... 
wanted to put it in some contest so wanted to know - otherwise i need to change ideas...

**Comment by xsalazar** [comment]
Not sure I can help you! I would say you might have better luck reaching out to someone at Google to ask acceptable-use if you're unsure.

**Comment by hacknorris-aka-penguin** [comment]
ok, thx

**Comment by gingerbeardman** [comment]
I had the same question. 

best I can find is https://developers.googleblog.com/en/updates-to-emoji-new-characters-new-animation-new-color-customization-and-more/

which says CC BY 4.0 license
