### ISSUE TITLE
New emoji combinations

### ISSUE THREAD

**Issue by cyb3rko** [xsalazar/emoji-kitchen#39]
With the newest GBoard update there are new emoji combinations.
https://9to5google.com/2022/03/11/gboard-emoji-kitchen-list/

Here are the new emojis, which can be combined with others

![Screenshot_20220313-105900.png](https://user-images.githubusercontent.com/46033730/158054422-6f43cfbe-f97e-459e-9e89-fd819f675c16.png)

**Comment by xsalazar** [comment]
@cyb3rko Just deployed a fix with the missing emoji! I searched their API for a newer release date, but only found images for `20220203` which looks like a lot of new emojis only got like 9 valid combos each and all are pretty poor compared to the earlier releases.

If you come across anything I'm missing, let me know the combo, and I can scrape any missing data!

🙇 Thank you for your contribution in pointing this out! I appreciate you

![image](https://user-images.githubusercontent.com/14851080/158318968-ba28d3fb-685d-4fa3-8ea8-59f1b4e3d71e.png)

**Comment by cyb3rko** [comment]
Awesome 👍🏻
