### ISSUE TITLE
Emoji Search by Name

### ISSUE THREAD

**Issue by Nebukadneza** [xsalazar/emoji-kitchen#424]
Coming from usual emoji pickers, I as a end-user, expected to find a search. Having a small search bar for both columns would be a great help to quickly find what you are looking for.

**Comment by xsalazar** [comment]
Thanks @Nebukadneza! You're not the first person to request this feature 🔍  The page was much more manageable at first with a small emoji set, but it's grown quite large now and finding the emoji you want can be tedious.

I've been playing with ideas to accomplish this, so stay tuned!

**Comment by dieseltravis** [comment]
The attached JSON file might be helpful for getting the friendly emoji names from the code value.
[emojis-names.zip](https://github.com/xsalazar/emoji-kitchen/files/12482259/emojis-names.zip)

**Comment by xsalazar** [comment]
Just wanted to keep the thread updated that I am making progress on this and hope to have something new in the next week or two 🤞 🔍

**Comment by xsalazar** [comment]
Just wanted to let you know that I just shipped some new features that hopefully accomplish what y'all are looking for 🙇 I appreciate your patience, and I'd love any feedback if this still doesn't totally work how you'd imagine!

**Comment by Nebukadneza** [comment]
That’s quite cool, the usability is nice, and it’s easy and quick to get the results wanted. Nice one, thanks a lot!
