### ISSUE TITLE
Two 404 Errors

### ISSUE THREAD

**Issue by dieseltravis** [xsalazar/emoji-kitchen#481]
Two combinations that I've tried have resulted in 404 broken images:

hair pick + trash can
![image](https://github.com/xsalazar/emoji-kitchen/assets/17863/e4c369a1-ac0d-43b1-af46-b9f4c5119e40)
https://www.gstatic.com/android/keyboard/emojikitchen/20230418/u1f5d1-ufe0f/u1f5d1-ufe0f_u1faae.png

hair pick + mouse trap
![image](https://github.com/xsalazar/emoji-kitchen/assets/17863/5ecd2130-fd27-4adf-85a9-98067edd36bb)
https://www.gstatic.com/android/keyboard/emojikitchen/20230418/u1faa4/u1faa4_u1faae.png

**Comment by xsalazar** [comment]
Ah, I think these might have been removed after some inferred negative connotations from what was initially released. I'll go ahead and remove these from the data set sometime today, so they won't show up as potentially valid combinations

**Comment by xsalazar** [comment]
Updated the data and it should be live now! Thanks for the heads up -- feel free to open any more issues if you see something broken/missing/incorrect.
