### ISSUE TITLE
"Randomize" button?

### ISSUE THREAD

**Issue by will-ca** [xsalazar/emoji-kitchen#492]
> There are currently just over 30,000 possible valid combinations showcasing the unique illustrations and combined emoji!

Well, we're never going to get around to all the really funny ones if we have to try them all one-by-one.

Since different first operand emojis have different numbers of possible second operands, you probably want to weight it to make sure combinations have equal probabilities.

**Comment by xsalazar** [comment]
Just wanted to let you know that I just shipped some new features that hopefully accomplish what you're looking for 🙇 I appreciate your patience, and I'd love any feedback if this still doesn't totally work how you'd imagine!
