### ISSUE TITLE
3D Versions

### ISSUE THREAD

**Issue by duckodas** [xsalazar/emoji-kitchen#536]
Will there be 3d versions of the emojis soon or in the future?

**Comment by xsalazar** [comment]
👋 Are these versions that already exist? Or are you wondering if there will ever be 3D versions in the future?

If the former, feel free to share them with me, and I can figure out if they're more widely available. If the latter, I have no idea! I only maintain whatever is available through Google's currently supported emoji 🙇

**Comment by duckodas** [comment]
> 👋 Are these versions that already exist? Or are you wondering if there will ever be 3D versions in the future?
> 
> If the former, feel free to share them with me, and I can figure out if they're more widely available. If the latter, I have no idea! I only maintain whatever is available through Google's currently supported emoji 🙇

They do exist but not able to make them on this site and idk if its supported by google to do this tho

**Comment by xsalazar** [comment]
Are you talking about [these](https://googlefonts.github.io/noto-emoji-animation/)? Otherwise, I'm still not sure what you're referencing without a link or some screenshots 😞

**Comment by duckodas** [comment]
> Are you talking about [these](https://googlefonts.github.io/noto-emoji-animation/)? Otherwise, I'm still not sure what you're referencing without a link or some screenshots 😞

Nop, they kinda look like [this](<https://miro.medium.com/v2/resize:fit:4800/format:webp/1*0IMvu324nfSWAGvm8RP5mA.png>)

**Comment by xsalazar** [comment]
AH those are Microsoft's Fluent Emoji. Conveniently, I also have a website here: https://fluentemoji.com/ where you can view and download those. [This](https://animated-fluent-emoji.vercel.app/) website is also really nice to view the animated versions until I figure out how to get those on my page as well.

Hopefully that helps!

**Comment by duckodas** [comment]
> AH those are Microsoft's Fluent Emoji. Conveniently, I also have a website here: https://fluentemoji.com/ where you can view and download those. [This](https://animated-fluent-emoji.vercel.app/) website is also really nice to view the animated versions until I figure out how to get those on my page as well.
> 
> Hopefully that helps!

Ah okay thanks!
