### ISSUE TITLE
How to Add a New Emoji: 🔩 (Nut and Bolt)

### ISSUE THREAD

**Issue by huglemon** [xsalazar/emoji-kitchen#784]
I would like to contribute to the project by adding a new emoji, the "Nut and Bolt" (🔩), to the existing list of supported emojis. 
How can I do it?
Thx.

**Comment by xsalazar** [comment]
Thanks for your interest @huglemon! Unfortunately, this is just the online browser into the supported emoji combinations provided by Google. I keep it as up-to-date as possible, but I'm at the whims of when/if they release support for any particular emoji.

I'll keep this post in mind if they ever add support for this and be sure to let you know!
